import { useEffect, useState } from 'react'
import { Activity, TrendingUp, TrendingDown, Minus } from 'lucide-react'

interface Signal {
  pair: string
  direction: 'bullish' | 'bearish' | 'neutral'
  confidence: number
  timeframe: string
  engines: string[]
}

export default function Signals() {
  const [signals, setSignals] = useState<Signal[]>([])

  useEffect(() => {
    // Demo data - would be fetched from backend
    setSignals([
      { pair: 'EURUSD', direction: 'bullish', confidence: 85, timeframe: '1D', engines: ['Elliott', 'ICT'] },
      { pair: 'GBPUSD', direction: 'bullish', confidence: 78, timeframe: '1D', engines: ['Wyckoff', 'Factors'] },
      { pair: 'USDJPY', direction: 'bearish', confidence: 72, timeframe: '4H', engines: ['Elliott'] },
      { pair: 'XAUUSD', direction: 'neutral', confidence: 52, timeframe: '1D', engines: ['ICT'] },
      { pair: 'BTCUSD', direction: 'bullish', confidence: 65, timeframe: '1D', engines: ['Wyckoff'] },
    ])
  }, [])

  const getDirectionIcon = (dir: string) => {
    switch (dir) {
      case 'bullish': return <TrendingUp className="w-5 h-5 text-green-600" />
      case 'bearish': return <TrendingDown className="w-5 h-5 text-red-600" />
      default: return <Minus className="w-5 h-5 text-gray-500" />
    }
  }

  const getDirectionClass = (dir: string) => {
    switch (dir) {
      case 'bullish': return 'bg-green-50 text-green-700 border-green-200'
      case 'bearish': return 'bg-red-50 text-red-700 border-red-200'
      default: return 'bg-gray-50 text-gray-700 border-gray-200'
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">Trading Signals</h1>
        <div className="flex gap-2">
          <select className="px-4 py-2 border rounded-lg text-sm">
            <option>All Timeframes</option>
            <option>1H</option>
            <option>4H</option>
            <option>1D</option>
          </select>
          <select className="px-4 py-2 border rounded-lg text-sm">
            <option>All Pairs</option>
            <option>Forex Majors</option>
            <option>Commodities</option>
            <option>Crypto</option>
          </select>
        </div>
      </div>

      <div className="grid gap-4">
        {signals.map((signal) => (
          <div 
            key={signal.pair} 
            className={`p-6 border rounded-xl ${getDirectionClass(signal.direction)}`}
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="p-2 bg-white rounded-lg shadow-sm">
                  {getDirectionIcon(signal.direction)}
                </div>
                <div>
                  <h3 className="text-lg font-semibold">{signal.pair}</h3>
                  <p className="text-sm opacity-75">{signal.timeframe} timeframe</p>
                </div>
              </div>
              
              <div className="flex items-center gap-6">
                <div className="text-right">
                  <p className="text-sm opacity-75">Confidence</p>
                  <p className="text-xl font-bold">{signal.confidence}%</p>
                </div>
                <div className="text-right">
                  <p className="text-sm opacity-75">Engines</p>
                  <div className="flex gap-1 mt-1">
                    {signal.engines.map((e) => (
                      <span key={e} className="px-2 py-1 bg-white rounded text-xs font-medium">
                        {e}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="p-6 bg-blue-50 rounded-xl border border-blue-100">
        <div className="flex items-start gap-3">
          <Activity className="w-5 h-5 text-blue-600 mt-0.5" />
          <div>
            <h3 className="font-semibold text-blue-900">Signal Methodology</h3>
            <p className="text-sm text-blue-700 mt-1">
              Signals are generated by combining outputs from Elliott Wave, Wyckoff, ICT, and Multi-Factor engines. 
              Each signal includes confidence score based on engine agreement and market conditions.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
