// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (user_id, action, resource, details, ip_address, user_agent, hash_prev, hash_self)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateAuditLogParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Resource  string      `json:"resource"`
	Details   string      `json:"details"`
	IpAddress *string     `json:"ip_address"`
	UserAgent *string     `json:"user_agent"`
	HashPrev  []byte      `json:"hash_prev"`
	HashSelf  []byte      `json:"hash_self"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Resource,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
		arg.HashPrev,
		arg.HashSelf,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, user_id, action, resource, details, ip_address, user_agent, created_at, hash_prev, hash_self FROM audit_logs WHERE id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Resource,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.HashPrev,
		&i.HashSelf,
	)
	return i, err
}

const getLastAuditLog = `-- name: GetLastAuditLog :one
SELECT id, user_id, action, resource, details, ip_address, user_agent, created_at, hash_prev, hash_self FROM audit_logs ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLastAuditLog(ctx context.Context) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getLastAuditLog)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Resource,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.HashPrev,
		&i.HashSelf,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, resource, details, ip_address, user_agent, created_at, hash_prev, hash_self FROM audit_logs
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::text = '' OR action = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY id DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsParams struct {
	Column1 uuid.UUID          `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Resource,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.HashPrev,
			&i.HashSelf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
