// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET status = 'banned', updated_at = NOW() WHERE id = $1
`

func (q *Queries) BanUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, banUser, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_resets (token_hash, user_id, purpose)
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	Purpose   string    `json:"purpose"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.Purpose)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (session_id, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING jti
`

type CreateRefreshTokenParams struct {
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.SessionID, arg.UserID, arg.ExpiresAt)
	var jti uuid.UUID
	err := row.Scan(&jti)
	return jti, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, user_agent, ip)
VALUES ($1, $2, $3)
RETURNING id, user_id, user_agent, ip, created_at, last_seen_at, revoked_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	UserAgent string      `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.UserAgent, arg.Ip)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, username, display_name, password_hash, locale, timezone, code_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, email, email_verified_at, username, display_name, password_hash, password_version, role, status, locale, timezone, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at, code_id
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	Username     *string `json:"username"`
	DisplayName  *string `json:"display_name"`
	PasswordHash string  `json:"password_hash"`
	Locale       string  `json:"locale"`
	Timezone     string  `json:"timezone"`
	CodeID       *string `json:"code_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Locale,
		arg.Timezone,
		arg.CodeID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.Role,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CodeID,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT token_hash, user_id, purpose, issued_at, expires_at, consumed_at FROM password_resets WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Purpose,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT jti, session_id, user_id, issued_at, expires_at, revoked_at, rotated_to FROM refresh_tokens WHERE jti = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, jti uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, jti)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.SessionID,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedTo,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, user_agent, ip, created_at, last_seen_at, revoked_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByCodeID = `-- name: GetUserByCodeID :one
SELECT id, email, email_verified_at, username, display_name, password_hash, password_version, role, status, locale, timezone, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at, code_id FROM users WHERE code_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByCodeID(ctx context.Context, codeID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCodeID, codeID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.Role,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CodeID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, username, display_name, password_hash, password_version, role, status, locale, timezone, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at, code_id FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.Role,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CodeID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, username, display_name, password_hash, password_version, role, status, locale, timezone, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at, code_id FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.Role,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CodeID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, email_verified_at, username, display_name, password_hash, password_version, role, status, locale, timezone, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at, code_id FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.Role,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CodeID,
	)
	return i, err
}

const isRefreshTokenRevoked = `-- name: IsRefreshTokenRevoked :one
SELECT EXISTS(SELECT 1 FROM refresh_tokens WHERE jti = $1 AND revoked_at IS NOT NULL)
`

func (q *Queries) IsRefreshTokenRevoked(ctx context.Context, jti uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isRefreshTokenRevoked, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isSessionRevoked = `-- name: IsSessionRevoked :one
SELECT EXISTS(SELECT 1 FROM sessions WHERE id = $1 AND revoked_at IS NOT NULL)
`

func (q *Queries) IsSessionRevoked(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionRevoked, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, user_agent, ip, created_at, last_seen_at, revoked_at FROM sessions WHERE user_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserAgent,
			&i.Ip,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified_at, username, display_name, password_hash, password_version, role, status, locale, timezone, totp_secret_enc, totp_enabled, created_at, updated_at, deleted_at, code_id FROM users
WHERE deleted_at IS NULL
  AND ($1::text = '' OR email ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR role = $2)
  AND ($3::boolean = false OR status = 'banned')
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListUsersParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 bool   `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.PasswordVersion,
			&i.Role,
			&i.Status,
			&i.Locale,
			&i.Timezone,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetTokenConsumed = `-- name: MarkPasswordResetTokenConsumed :exec
UPDATE password_resets SET consumed_at = NOW() WHERE token_hash = $1
`

func (q *Queries) MarkPasswordResetTokenConsumed(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenConsumed, tokenHash)
	return err
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens SET rotated_to = $2 WHERE jti = $1
`

type MarkRefreshTokenRotatedParams struct {
	Jti       uuid.UUID   `json:"jti"`
	RotatedTo pgtype.UUID `json:"rotated_to"`
}

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, arg.Jti, arg.RotatedTo)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE user_id = $1
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = NOW() WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE jti = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, jti uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, jti)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET status = 'active', updated_at = NOW() WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unbanUser, id)
	return err
}

const updateEmailVerifiedAt = `-- name: UpdateEmailVerifiedAt :exec
UPDATE users SET email_verified_at = $2, updated_at = NOW() WHERE id = $1
`

type UpdateEmailVerifiedAtParams struct {
	ID              uuid.UUID          `json:"id"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) UpdateEmailVerifiedAt(ctx context.Context, arg UpdateEmailVerifiedAtParams) error {
	_, err := q.db.Exec(ctx, updateEmailVerifiedAt, arg.ID, arg.EmailVerifiedAt)
	return err
}

const updatePasswordVersion = `-- name: UpdatePasswordVersion :exec
UPDATE users SET password_version = password_version + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdatePasswordVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updatePasswordVersion, id)
	return err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions SET last_seen_at = NOW(), ip = $2 WHERE id = $1
`

type UpdateSessionLastSeenParams struct {
	ID uuid.UUID   `json:"id"`
	Ip *netip.Addr `json:"ip"`
}

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, arg UpdateSessionLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, arg.ID, arg.Ip)
	return err
}

const updateUserCodeID = `-- name: UpdateUserCodeID :exec
UPDATE users SET code_id = $2, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserCodeIDParams struct {
	ID     uuid.UUID `json:"id"`
	CodeID *string   `json:"code_id"`
}

func (q *Queries) UpdateUserCodeID(ctx context.Context, arg UpdateUserCodeIDParams) error {
	_, err := q.db.Exec(ctx, updateUserCodeID, arg.ID, arg.CodeID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, password_version = password_version + 1, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
