// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: byok.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateUserAIKey = `-- name: CreateOrUpdateUserAIKey :exec
INSERT INTO user_ai_keys (user_id, provider, key_enc, key_fingerprint)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, provider) DO UPDATE
SET key_enc = $3, key_fingerprint = $4, updated_at = NOW()
`

type CreateOrUpdateUserAIKeyParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	KeyEnc         []byte    `json:"key_enc"`
	KeyFingerprint string    `json:"key_fingerprint"`
}

func (q *Queries) CreateOrUpdateUserAIKey(ctx context.Context, arg CreateOrUpdateUserAIKeyParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateUserAIKey,
		arg.UserID,
		arg.Provider,
		arg.KeyEnc,
		arg.KeyFingerprint,
	)
	return err
}

const deleteUserAIKey = `-- name: DeleteUserAIKey :exec
DELETE FROM user_ai_keys WHERE user_id = $1 AND provider = $2
`

type DeleteUserAIKeyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) DeleteUserAIKey(ctx context.Context, arg DeleteUserAIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteUserAIKey, arg.UserID, arg.Provider)
	return err
}

const getUserAIKey = `-- name: GetUserAIKey :one
SELECT user_id, provider, key_enc, key_fingerprint, last_verified_at, last_error, created_at, updated_at FROM user_ai_keys WHERE user_id = $1 AND provider = $2
`

type GetUserAIKeyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetUserAIKey(ctx context.Context, arg GetUserAIKeyParams) (UserAiKey, error) {
	row := q.db.QueryRow(ctx, getUserAIKey, arg.UserID, arg.Provider)
	var i UserAiKey
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.KeyEnc,
		&i.KeyFingerprint,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAIKeys = `-- name: ListActiveAIKeys :many
SELECT user_id, provider, key_enc, key_fingerprint, last_verified_at, last_error, created_at, updated_at FROM user_ai_keys WHERE last_error IS NULL OR last_error = ''
`

func (q *Queries) ListActiveAIKeys(ctx context.Context) ([]UserAiKey, error) {
	rows, err := q.db.Query(ctx, listActiveAIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAiKey
	for rows.Next() {
		var i UserAiKey
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.KeyEnc,
			&i.KeyFingerprint,
			&i.LastVerifiedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIKeyError = `-- name: UpdateAIKeyError :exec
UPDATE user_ai_keys SET last_error = $3 WHERE user_id = $1 AND provider = $2
`

type UpdateAIKeyErrorParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Provider  string    `json:"provider"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) UpdateAIKeyError(ctx context.Context, arg UpdateAIKeyErrorParams) error {
	_, err := q.db.Exec(ctx, updateAIKeyError, arg.UserID, arg.Provider, arg.LastError)
	return err
}

const updateAIKeyHealth = `-- name: UpdateAIKeyHealth :exec
UPDATE user_ai_keys 
SET last_verified_at = COALESCE($3, last_verified_at), 
    last_error = COALESCE($4, last_error),
    updated_at = NOW()
WHERE user_id = $1 AND provider = $2
`

type UpdateAIKeyHealthParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	LastError      *string            `json:"last_error"`
}

func (q *Queries) UpdateAIKeyHealth(ctx context.Context, arg UpdateAIKeyHealthParams) error {
	_, err := q.db.Exec(ctx, updateAIKeyHealth,
		arg.UserID,
		arg.Provider,
		arg.LastVerifiedAt,
		arg.LastError,
	)
	return err
}

const updateAIKeyVerified = `-- name: UpdateAIKeyVerified :exec
UPDATE user_ai_keys SET last_verified_at = NOW(), last_error = NULL WHERE user_id = $1 AND provider = $2
`

type UpdateAIKeyVerifiedParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) UpdateAIKeyVerified(ctx context.Context, arg UpdateAIKeyVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateAIKeyVerified, arg.UserID, arg.Provider)
	return err
}
