// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiCache struct {
	Fingerprint string             `json:"fingerprint"`
	Operation   *string            `json:"operation"`
	Model       *string            `json:"model"`
	Result      *string            `json:"result"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type AiMemory struct {
	UserID    string             `json:"user_id"`
	Path      string             `json:"path"`
	Content   *string            `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AiUsage struct {
	ID               int64              `json:"id"`
	UserID           *string            `json:"user_id"`
	Model            *string            `json:"model"`
	Operation        *string            `json:"operation"`
	PromptTokens     *int32             `json:"prompt_tokens"`
	CompletionTokens *int32             `json:"completion_tokens"`
	Cached           *bool              `json:"cached"`
	DurationMs       *int32             `json:"duration_ms"`
	Error            *string            `json:"error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Resource  string             `json:"resource"`
	Details   string             `json:"details"`
	IpAddress *string            `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	HashPrev  []byte             `json:"hash_prev"`
	HashSelf  []byte             `json:"hash_self"`
}

type BacktestJob struct {
	JobID       uuid.UUID          `json:"job_id"`
	UserID      *string            `json:"user_id"`
	Type        *string            `json:"type"`
	Request     []byte             `json:"request"`
	Status      *string            `json:"status"`
	Progress    *float64           `json:"progress"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       *string            `json:"error"`
}

type BacktestResult struct {
	JobID       uuid.UUID          `json:"job_id"`
	Summary     []byte             `json:"summary"`
	EquityCurve []byte             `json:"equity_curve"`
	Trades      []byte             `json:"trades"`
	Detailed    []byte             `json:"detailed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BisCreditGap struct {
	Date      pgtype.Date `json:"date"`
	Country   string      `json:"country"`
	GapPct    *float64    `json:"gap_pct"`
	RiskLabel *string     `json:"risk_label"`
}

type BisPolicyRate struct {
	Date     pgtype.Date `json:"date"`
	Currency string      `json:"currency"`
	Rate     *float64    `json:"rate"`
}

type BisReer struct {
	Date     pgtype.Date `json:"date"`
	Currency string      `json:"currency"`
	Reer     *float64    `json:"reer"`
	ZScore   *float64    `json:"z_score"`
}

type BotBinding struct {
	ID               uuid.UUID          `json:"id"`
	Platform         string             `json:"platform"`
	ExternalUserID   string             `json:"external_user_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ExternalUsername *string            `json:"external_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CalendarEvent struct {
	EventID         string             `json:"event_id"`
	Title           string             `json:"title"`
	Country         *string            `json:"country"`
	Currency        *string            `json:"currency"`
	Impact          *string            `json:"impact"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	PreviousValue   *string            `json:"previous_value"`
	ForecastValue   *string            `json:"forecast_value"`
	ActualValue     *string            `json:"actual_value"`
	ImpactDirection *int16             `json:"impact_direction"`
	SurpriseScore   *float64           `json:"surprise_score"`
	SurpriseLabel   *string            `json:"surprise_label"`
	RevisionLabel   *string            `json:"revision_label"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CalendarEventTitle struct {
	EventID     string             `json:"event_id"`
	Lang        string             `json:"lang"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Source      string             `json:"source"`
	Confidence  *float64           `json:"confidence"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
}

type CalendarSurpriseHistory struct {
	ID          int64              `json:"id"`
	EventName   *string            `json:"event_name"`
	Currency    *string            `json:"currency"`
	ReleasedAt  pgtype.Timestamptz `json:"released_at"`
	ActualVal   *float64           `json:"actual_val"`
	ForecastVal *float64           `json:"forecast_val"`
	Diff        *float64           `json:"diff"`
	Sigma       *float64           `json:"sigma"`
}

type CarryRate struct {
	Date        pgtype.Date `json:"date"`
	Currency    string      `json:"currency"`
	Rate        *float64    `json:"rate"`
	VsUsdSpread *float64    `json:"vs_usd_spread"`
}

type CotAnalysis struct {
	ReportDate     pgtype.Date `json:"report_date"`
	ContractCode   string      `json:"contract_code"`
	NetPosition    *int64      `json:"net_position"`
	CotIndex       *float64    `json:"cot_index"`
	Direction      *string     `json:"direction"`
	SentimentScore *float64    `json:"sentiment_score"`
	WowChange      *int64      `json:"wow_change"`
	Zscore         *float64    `json:"zscore"`
	Percentile     *float64    `json:"percentile"`
}

type CotCalibration struct {
	SignalType string             `json:"signal_type"`
	PlattA     *float64           `json:"platt_a"`
	PlattB     *float64           `json:"platt_b"`
	WinRate    *float64           `json:"win_rate"`
	SampleSize *int32             `json:"sample_size"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CotRecord struct {
	ReportDate   pgtype.Date `json:"report_date"`
	ContractCode string      `json:"contract_code"`
	Currency     *string     `json:"currency"`
	NoncommLong  *int64      `json:"noncomm_long"`
	NoncommShort *int64      `json:"noncomm_short"`
	CommLong     *int64      `json:"comm_long"`
	CommShort    *int64      `json:"comm_short"`
	DealerLong   *int64      `json:"dealer_long"`
	DealerShort  *int64      `json:"dealer_short"`
	LevfundLong  *int64      `json:"levfund_long"`
	LevfundShort *int64      `json:"levfund_short"`
	MmLong       *int64      `json:"mm_long"`
	MmShort      *int64      `json:"mm_short"`
	SwapLong     *int64      `json:"swap_long"`
	SwapShort    *int64      `json:"swap_short"`
	TotalOi      *int64      `json:"total_oi"`
	RawJson      []byte      `json:"raw_json"`
}

type CotSignalOutcome struct {
	SignalID      int64              `json:"signal_id"`
	SignalType    string             `json:"signal_type"`
	ContractCode  string             `json:"contract_code"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	RawConfidence *float64           `json:"raw_confidence"`
	Return1w      *float64           `json:"return_1w"`
	Return2w      *float64           `json:"return_2w"`
	Return4w      *float64           `json:"return_4w"`
	Win           *bool              `json:"win"`
	EvaluatedAt   pgtype.Timestamptz `json:"evaluated_at"`
}

type DataSnapshot struct {
	Time         pgtype.Timestamptz `json:"time"`
	Source       string             `json:"source"`
	SeriesID     string             `json:"series_id"`
	ValueNumeric *float64           `json:"value_numeric"`
	ValueText    *string            `json:"value_text"`
	RawJson      []byte             `json:"raw_json"`
	FetchedAt    pgtype.Timestamptz `json:"fetched_at"`
}

type DefiSnapshot struct {
	Time         pgtype.Timestamptz `json:"time"`
	TotalTvl     *float64           `json:"total_tvl"`
	TvlChange24h *float64           `json:"tvl_change_24h"`
	TvlChange7d  *float64           `json:"tvl_change_7d"`
	DexVol24h    *float64           `json:"dex_vol_24h"`
	StablecoinMc *float64           `json:"stablecoin_mc"`
	Raw          []byte             `json:"raw"`
}

type DvolSnapshot struct {
	Time         pgtype.Timestamptz `json:"time"`
	Currency     string             `json:"currency"`
	CurrentIv    *float64           `json:"current_iv"`
	Change24hPct *float64           `json:"change_24h_pct"`
	IvHvSpread   *float64           `json:"iv_hv_spread"`
	IvHvRatio    *float64           `json:"iv_hv_ratio"`
	Spike        *bool              `json:"spike"`
}

type ElliottCount struct {
	ID         int64              `json:"id"`
	Symbol     *string            `json:"symbol"`
	Timeframe  *string            `json:"timeframe"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
	WaveType   *string            `json:"wave_type"`
	Waves      []byte             `json:"waves"`
	Valid      *bool              `json:"valid"`
	Targets    []byte             `json:"targets"`
	Confidence *float64           `json:"confidence"`
}

type EventImpactRecord struct {
	EventID     string             `json:"event_id"`
	Window      string             `json:"window"`
	Symbol      string             `json:"symbol"`
	PriceBefore *float64           `json:"price_before"`
	PriceAfter  *float64           `json:"price_after"`
	PctChange   *float64           `json:"pct_change"`
	RecordedAt  pgtype.Timestamptz `json:"recorded_at"`
}

type FactorRanking struct {
	Time       pgtype.Timestamptz `json:"time"`
	SnapshotID int64              `json:"snapshot_id"`
	Weights    []byte             `json:"weights"`
}

type FactorRankingEntry struct {
	SnapshotID int64    `json:"snapshot_id"`
	Symbol     string   `json:"symbol"`
	Rank       *int32   `json:"rank"`
	RawScore   *float64 `json:"raw_score"`
	NormScore  *float64 `json:"norm_score"`
	Breakdown  []byte   `json:"breakdown"`
}

type FedSpeech struct {
	Guid        string             `json:"guid"`
	Title       *string            `json:"title"`
	Speaker     *string            `json:"speaker"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Url         *string            `json:"url"`
	Content     *string            `json:"content"`
	Tone        *string            `json:"tone"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
}

type FedWatchProbability struct {
	SnapshotAt    pgtype.Timestamptz `json:"snapshot_at"`
	MeetingDate   pgtype.Date        `json:"meeting_date"`
	RateChangeBps int32              `json:"rate_change_bps"`
	Probability   *float64           `json:"probability"`
}

type FetchJob struct {
	ID              int64              `json:"id"`
	JobType         string             `json:"job_type"`
	Source          string             `json:"source"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Status          *string            `json:"status"`
	ErrorMessage    *string            `json:"error_message"`
	RecordsInserted *int32             `json:"records_inserted"`
	RecordsUpdated  *int32             `json:"records_updated"`
	DurationMs      *int32             `json:"duration_ms"`
}

type FlowDivergenceHistory struct {
	Time         pgtype.Timestamptz `json:"time"`
	PairA        string             `json:"pair_a"`
	PairB        string             `json:"pair_b"`
	Corr         *float64           `json:"corr"`
	BaselineMean *float64           `json:"baseline_mean"`
	BaselineStd  *float64           `json:"baseline_std"`
	ZScore       *float64           `json:"z_score"`
	LeadLag      *int32             `json:"lead_lag"`
}

type FredDailyAgg struct {
	Day          interface{} `json:"day"`
	Source       string      `json:"source"`
	SeriesID     string      `json:"series_id"`
	DailyValue   interface{} `json:"daily_value"`
	Observations int64       `json:"observations"`
}

type GexSnapshot struct {
	Time        pgtype.Timestamptz `json:"time"`
	Symbol      string             `json:"symbol"`
	SpotPrice   *float64           `json:"spot_price"`
	TotalGex    *float64           `json:"total_gex"`
	FlipLevel   *float64           `json:"flip_level"`
	MaxCallWall *float64           `json:"max_call_wall"`
	MaxPutWall  *float64           `json:"max_put_wall"`
	Levels      []byte             `json:"levels"`
}

type IctStructure struct {
	ID          int64              `json:"id"`
	Symbol      *string            `json:"symbol"`
	Timeframe   *string            `json:"timeframe"`
	Type        *string            `json:"type"`
	FormedAt    pgtype.Timestamptz `json:"formed_at"`
	High        *float64           `json:"high"`
	Low         *float64           `json:"low"`
	Direction   *string            `json:"direction"`
	Mitigated   *bool              `json:"mitigated"`
	MitigatedAt pgtype.Timestamptz `json:"mitigated_at"`
	Reversed    *bool              `json:"reversed"`
	Raw         []byte             `json:"raw"`
}

type ImfWeo struct {
	Country    string   `json:"country"`
	Indicator  string   `json:"indicator"`
	Year       int32    `json:"year"`
	IsForecast *bool    `json:"is_forecast"`
	Value      *float64 `json:"value"`
	Vintage    string   `json:"vintage"`
}

type IntermarketCorrelation struct {
	Time           pgtype.Timestamptz `json:"time"`
	PairA          string             `json:"pair_a"`
	PairB          string             `json:"pair_b"`
	WindowDays     int32              `json:"window_days"`
	Correlation    *float64           `json:"correlation"`
	HistoricalMean *float64           `json:"historical_mean"`
	HistoricalStd  *float64           `json:"historical_std"`
	ZScore         *float64           `json:"z_score"`
	IsBreak        *bool              `json:"is_break"`
}

type IvSkewHistory struct {
	Time      pgtype.Timestamptz `json:"time"`
	Symbol    string             `json:"symbol"`
	PcIvRatio *float64           `json:"pc_iv_ratio"`
	SkewSlope *float64           `json:"skew_slope"`
	Smile     []byte             `json:"smile"`
	TermSlope *float64           `json:"term_slope"`
	FlipEvent *string            `json:"flip_event"`
}

type MacroIndicator struct {
	Source    string             `json:"source"`
	Indicator string             `json:"indicator"`
	Region    string             `json:"region"`
	Period    pgtype.Date        `json:"period"`
	Value     *float64           `json:"value"`
	Metadata  []byte             `json:"metadata"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type MacroRegimeHistory struct {
	Time    pgtype.Timestamptz `json:"time"`
	Regime  string             `json:"regime"`
	Score   *float64           `json:"score"`
	Details []byte             `json:"details"`
}

type MicroSnapshot struct {
	Time        pgtype.Timestamptz `json:"time"`
	Symbol      string             `json:"symbol"`
	ObiTop10    *float64           `json:"obi_top10"`
	SpreadBps   *float64           `json:"spread_bps"`
	BidDepth    *float64           `json:"bid_depth"`
	AskDepth    *float64           `json:"ask_depth"`
	StressScore *float64           `json:"stress_score"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Category  string             `json:"category"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	Priority  *string            `json:"priority"`
	Severity  string             `json:"severity"`
	DedupKey  *string            `json:"dedup_key"`
	IsRead    *bool              `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type UserNotificationPref struct {
	UserID       uuid.UUID          `json:"user_id"`
	EnabledTypes []string           `json:"enabled_types"`
	MinSeverity  string             `json:"min_severity"`
	QuietStart   pgtype.Time        `json:"quiet_start"`
	QuietEnd     pgtype.Time        `json:"quiet_end"`
	Timezone     string             `json:"timezone"`
	PushEnabled  bool               `json:"push_enabled"`
	EmailEnabled bool               `json:"email_enabled"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OnchainMetric struct {
	Date         pgtype.Date `json:"date"`
	Asset        string      `json:"asset"`
	FlowIn       *float64    `json:"flow_in"`
	FlowOut      *float64    `json:"flow_out"`
	NetFlow      *float64    `json:"net_flow"`
	ActiveAddr   *int64      `json:"active_addr"`
	TxCount      *int64      `json:"tx_count"`
	OnchainScore *float64    `json:"onchain_score"`
}

type OrderflowAbsorption struct {
	ID        int64              `json:"id"`
	Time      pgtype.Timestamptz `json:"time"`
	Symbol    *string            `json:"symbol"`
	Price     *float64           `json:"price"`
	Direction *string            `json:"direction"`
	Strength  *float64           `json:"strength"`
	Volume    *float64           `json:"volume"`
}

type PasswordReset struct {
	TokenHash  []byte             `json:"token_hash"`
	UserID     uuid.UUID          `json:"user_id"`
	Purpose    string             `json:"purpose"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type Playbook struct {
	ID          int64              `json:"id"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	UserID      *string            `json:"user_id"`
	Regime      *string            `json:"regime"`
	Entries     []byte             `json:"entries"`
	GlobalRisk  []byte             `json:"global_risk"`
	Weights     []byte             `json:"weights"`
}

type PlaybookDecision struct {
	ID          int64              `json:"id"`
	PlaybookID  *int64             `json:"playbook_id"`
	UserID      *string            `json:"user_id"`
	Symbol      *string            `json:"symbol"`
	Decision    *string            `json:"decision"`
	ActualEntry *float64           `json:"actual_entry"`
	ActualStop  *float64           `json:"actual_stop"`
	Notes       *string            `json:"notes"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
}

type PriceDaily struct {
	Time   pgtype.Timestamptz `json:"time"`
	Symbol string             `json:"symbol"`
	Open   *float64           `json:"open"`
	High   *float64           `json:"high"`
	Low    *float64           `json:"low"`
	Close  *float64           `json:"close"`
	Volume *float64           `json:"volume"`
	Source *string            `json:"source"`
}

type PriceIntraday struct {
	Time     pgtype.Timestamptz `json:"time"`
	Symbol   string             `json:"symbol"`
	Interval string             `json:"interval"`
	Open     *float64           `json:"open"`
	High     *float64           `json:"high"`
	Low      *float64           `json:"low"`
	Close    *float64           `json:"close"`
	Volume   *float64           `json:"volume"`
	Source   *string            `json:"source"`
}

type PriceWeekly struct {
	Week   interface{} `json:"week"`
	Symbol string      `json:"symbol"`
	Open   interface{} `json:"open"`
	High   interface{} `json:"high"`
	Low    interface{} `json:"low"`
	Close  interface{} `json:"close"`
	Volume int64       `json:"volume"`
}

type RefreshToken struct {
	Jti       uuid.UUID          `json:"jti"`
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	RotatedTo pgtype.UUID        `json:"rotated_to"`
}

type RegimeOverlayHistory struct {
	Time            pgtype.Timestamptz `json:"time"`
	Symbol          string             `json:"symbol"`
	Timeframe       string             `json:"timeframe"`
	UnifiedScore    *float64           `json:"unified_score"`
	UnifiedLabel    *string            `json:"unified_label"`
	HmmState        *string            `json:"hmm_state"`
	HmmConfidence   *float64           `json:"hmm_confidence"`
	HmmScore        *float64           `json:"hmm_score"`
	GarchRegime     *string            `json:"garch_regime"`
	VolRatio        *float64           `json:"vol_ratio"`
	GarchScore      *float64           `json:"garch_score"`
	AdxStrength     *string            `json:"adx_strength"`
	AdxValue        *float64           `json:"adx_value"`
	AdxScore        *float64           `json:"adx_score"`
	CotScore        *float64           `json:"cot_score"`
	AvailableModels []byte             `json:"available_models"`
}

type RegimeTransition struct {
	ID        int64              `json:"id"`
	Time      pgtype.Timestamptz `json:"time"`
	Symbol    *string            `json:"symbol"`
	Timeframe *string            `json:"timeframe"`
	FromLabel *string            `json:"from_label"`
	ToLabel   *string            `json:"to_label"`
	FromScore *float64           `json:"from_score"`
	ToScore   *float64           `json:"to_score"`
	Severity  *string            `json:"severity"`
}

type Sec13fHolding struct {
	InstitutionCik string             `json:"institution_cik"`
	Quarter        string             `json:"quarter"`
	Issuer         *string            `json:"issuer"`
	Cusip          string             `json:"cusip"`
	ValueUsd       *int64             `json:"value_usd"`
	Shares         *int64             `json:"shares"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
}

type SentimentSnapshot struct {
	Time          pgtype.Timestamptz `json:"time"`
	Score         *float64           `json:"score"`
	Regime        *string            `json:"regime"`
	PcRatio       *float64           `json:"pc_ratio"`
	PcPercentile  *float64           `json:"pc_percentile"`
	FearGreed     *float64           `json:"fear_greed"`
	RetailLongPct *float64           `json:"retail_long_pct"`
	InsiderNet    *float64           `json:"insider_net"`
	Raw           []byte             `json:"raw"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	UserAgent  string             `json:"user_agent"`
	Ip         *netip.Addr        `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type SignalCalibration struct {
	SignalType string             `json:"signal_type"`
	LogisticA  *float64           `json:"logistic_a"`
	LogisticB  *float64           `json:"logistic_b"`
	SampleSize *int32             `json:"sample_size"`
	WinRate    *float64           `json:"win_rate"`
	AvgReturn  *float64           `json:"avg_return"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SignalOutcome struct {
	SignalID       int64              `json:"signal_id"`
	Horizon        string             `json:"horizon"`
	ReturnPct      *float64           `json:"return_pct"`
	DirectionMatch *bool              `json:"direction_match"`
	EvaluatedAt    pgtype.Timestamptz `json:"evaluated_at"`
}

type SignalWeightConfig struct {
	ID        int32              `json:"id"`
	Name      *string            `json:"name"`
	Weights   []byte             `json:"weights"`
	IsActive  *bool              `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TaSignal struct {
	ID         int64              `json:"id"`
	Symbol     *string            `json:"symbol"`
	Timeframe  *string            `json:"timeframe"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	SignalType *string            `json:"signal_type"`
	Grade      *string            `json:"grade"`
	Direction  *string            `json:"direction"`
	EntryPrice *float64           `json:"entry_price"`
	StopLoss   *float64           `json:"stop_loss"`
	TakeProfit *float64           `json:"take_profit"`
	Metadata   []byte             `json:"metadata"`
}

type TreasuryAuction struct {
	Cusip        string      `json:"cusip"`
	SecurityType *string     `json:"security_type"`
	SecurityTerm *string     `json:"security_term"`
	AuctionDate  pgtype.Date `json:"auction_date"`
	HighYield    *float64    `json:"high_yield"`
	BidToCover   *float64    `json:"bid_to_cover"`
	IndirectPct  *float64    `json:"indirect_pct"`
	DemandLabel  *string     `json:"demand_label"`
}

type UnifiedSignal struct {
	ID             int64              `json:"id"`
	Symbol         string             `json:"symbol"`
	IssuedAt       pgtype.Timestamptz `json:"issued_at"`
	Recommendation *string            `json:"recommendation"`
	UnifiedScore   *float64           `json:"unified_score"`
	Confidence     *float64           `json:"confidence"`
	Components     []byte             `json:"components"`
	MissingSubsys  []string           `json:"missing_subsys"`
	WeightsUsed    []byte             `json:"weights_used"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Username        *string            `json:"username"`
	DisplayName     *string            `json:"display_name"`
	PasswordHash    string             `json:"password_hash"`
	PasswordVersion int32              `json:"password_version"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	Locale          string             `json:"locale"`
	Timezone        string             `json:"timezone"`
	TotpSecretEnc   []byte             `json:"totp_secret_enc"`
	TotpEnabled     *bool              `json:"totp_enabled"`
	CodeID          *string            `json:"code_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserAiKey struct {
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	KeyEnc         []byte             `json:"key_enc"`
	KeyFingerprint string             `json:"key_fingerprint"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	LastError      *string            `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type VixTermStructure struct {
	Time        pgtype.Timestamptz `json:"time"`
	Spot        *float64           `json:"spot"`
	M1          *float64           `json:"m1"`
	M2          *float64           `json:"m2"`
	M3          *float64           `json:"m3"`
	Vvix        *float64           `json:"vvix"`
	Vix9d       *float64           `json:"vix9d"`
	Vix3m       *float64           `json:"vix3m"`
	Skew        *float64           `json:"skew"`
	Ovx         *float64           `json:"ovx"`
	Gvz         *float64           `json:"gvz"`
	Rvx         *float64           `json:"rvx"`
	Move        *float64           `json:"move"`
	Contango    *bool              `json:"contango"`
	CrossRegime *string            `json:"cross_regime"`
	Raw         []byte             `json:"raw"`
}

type VolumeProfile struct {
	Time    pgtype.Timestamptz `json:"time"`
	Symbol  string             `json:"symbol"`
	Period  string             `json:"period"`
	Poc     *float64           `json:"poc"`
	Vah     *float64           `json:"vah"`
	Val     *float64           `json:"val"`
	Profile []byte             `json:"profile"`
}

type WalkforwardHistory struct {
	ID             int64              `json:"id"`
	FoldIdx        *int32             `json:"fold_idx"`
	TrainFrom      pgtype.Date        `json:"train_from"`
	TrainTo        pgtype.Date        `json:"train_to"`
	TestFrom       pgtype.Date        `json:"test_from"`
	TestTo         pgtype.Date        `json:"test_to"`
	OptimalWeights []byte             `json:"optimal_weights"`
	InSampleSharpe *float64           `json:"in_sample_sharpe"`
	OosSharpe      *float64           `json:"oos_sharpe"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WorldbankMacro struct {
	Country        string   `json:"country"`
	Currency       *string  `json:"currency"`
	Year           int32    `json:"year"`
	GdpGrowth      *float64 `json:"gdp_growth"`
	CurrentAccount *float64 `json:"current_account"`
	Cpi            *float64 `json:"cpi"`
	FxReserves     *float64 `json:"fx_reserves"`
}

type WyckoffEvent struct {
	ID         int64              `json:"id"`
	Symbol     *string            `json:"symbol"`
	Timeframe  *string            `json:"timeframe"`
	EventName  *string            `json:"event_name"`
	BarTime    pgtype.Timestamptz `json:"bar_time"`
	Price      *float64           `json:"price"`
	Volume     *float64           `json:"volume"`
	Confidence *float64           `json:"confidence"`
	Raw        []byte             `json:"raw"`
}

type WyckoffPhase struct {
	Time       pgtype.Timestamptz `json:"time"`
	Symbol     string             `json:"symbol"`
	Timeframe  string             `json:"timeframe"`
	Phase      *string            `json:"phase"`
	Confidence *float64           `json:"confidence"`
	CauseScore *float64           `json:"cause_score"`
}
