// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_prefs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserNotificationPrefs = `-- name: GetUserNotificationPrefs :one
SELECT user_id, enabled_types, min_severity, quiet_start, quiet_end, timezone,
       push_enabled, email_enabled, updated_at
  FROM user_notification_prefs
 WHERE user_id = $1
`

func (q *Queries) GetUserNotificationPrefs(ctx context.Context, userID uuid.UUID) (UserNotificationPref, error) {
	row := q.db.QueryRow(ctx, getUserNotificationPrefs, userID)
	var i UserNotificationPref
	err := row.Scan(
		&i.UserID,
		&i.EnabledTypes,
		&i.MinSeverity,
		&i.QuietStart,
		&i.QuietEnd,
		&i.Timezone,
		&i.PushEnabled,
		&i.EmailEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserNotificationPrefs = `-- name: UpsertUserNotificationPrefs :one
INSERT INTO user_notification_prefs (
    user_id, enabled_types, min_severity, quiet_start, quiet_end, timezone, push_enabled, email_enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET
    enabled_types = EXCLUDED.enabled_types,
    min_severity  = EXCLUDED.min_severity,
    quiet_start   = EXCLUDED.quiet_start,
    quiet_end     = EXCLUDED.quiet_end,
    timezone      = EXCLUDED.timezone,
    push_enabled  = EXCLUDED.push_enabled,
    email_enabled = EXCLUDED.email_enabled,
    updated_at    = NOW()
RETURNING user_id, enabled_types, min_severity, quiet_start, quiet_end, timezone,
          push_enabled, email_enabled, updated_at
`

type UpsertUserNotificationPrefsParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	EnabledTypes []string    `json:"enabled_types"`
	MinSeverity  string      `json:"min_severity"`
	QuietStart   pgtype.Time `json:"quiet_start"`
	QuietEnd     pgtype.Time `json:"quiet_end"`
	Timezone     string      `json:"timezone"`
	PushEnabled  bool        `json:"push_enabled"`
	EmailEnabled bool        `json:"email_enabled"`
}

func (q *Queries) UpsertUserNotificationPrefs(ctx context.Context, arg UpsertUserNotificationPrefsParams) (UserNotificationPref, error) {
	row := q.db.QueryRow(ctx, upsertUserNotificationPrefs,
		arg.UserID,
		arg.EnabledTypes,
		arg.MinSeverity,
		arg.QuietStart,
		arg.QuietEnd,
		arg.Timezone,
		arg.PushEnabled,
		arg.EmailEnabled,
	)
	var i UserNotificationPref
	err := row.Scan(
		&i.UserID,
		&i.EnabledTypes,
		&i.MinSeverity,
		&i.QuietStart,
		&i.QuietEnd,
		&i.Timezone,
		&i.PushEnabled,
		&i.EmailEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
