// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_state.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldPushStates = `-- name: DeleteOldPushStates :exec
DELETE FROM notification_push_state
 WHERE last_sent_at < $1
`

func (q *Queries) DeleteOldPushStates(ctx context.Context, lastSentAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldPushStates, lastSentAt)
	return err
}

const getPushState = `-- name: GetPushState :one
SELECT id, user_id, event_key, push_type, last_sent_at, payload_hash, created_at, updated_at
  FROM notification_push_state
 WHERE user_id = $1 AND event_key = $2 AND push_type = $3
`

type GetPushStateParams struct {
	UserID   uuid.UUID `json:"user_id"`
	EventKey string    `json:"event_key"`
	PushType string    `json:"push_type"`
}

func (q *Queries) GetPushState(ctx context.Context, arg GetPushStateParams) (NotificationPushState, error) {
	row := q.db.QueryRow(ctx, getPushState, arg.UserID, arg.EventKey, arg.PushType)
	var i NotificationPushState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventKey,
		&i.PushType,
		&i.LastSentAt,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPushStatesByUser = `-- name: ListPushStatesByUser :many
SELECT id, user_id, event_key, push_type, last_sent_at, payload_hash, created_at, updated_at
  FROM notification_push_state
 WHERE user_id = $1
 ORDER BY last_sent_at DESC
 LIMIT $2
`

type ListPushStatesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListPushStatesByUser(ctx context.Context, arg ListPushStatesByUserParams) ([]NotificationPushState, error) {
	rows, err := q.db.Query(ctx, listPushStatesByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPushState
	for rows.Next() {
		var i NotificationPushState
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventKey,
			&i.PushType,
			&i.LastSentAt,
			&i.PayloadHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushState = `-- name: UpsertPushState :one
INSERT INTO notification_push_state (user_id, event_key, push_type, last_sent_at, payload_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, event_key, push_type)
DO UPDATE SET last_sent_at = EXCLUDED.last_sent_at,
              payload_hash = EXCLUDED.payload_hash,
              updated_at = NOW()
RETURNING id, user_id, event_key, push_type, last_sent_at, payload_hash, created_at, updated_at
`

type UpsertPushStateParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	EventKey    string             `json:"event_key"`
	PushType    string             `json:"push_type"`
	LastSentAt  pgtype.Timestamptz `json:"last_sent_at"`
	PayloadHash string             `json:"payload_hash"`
}

func (q *Queries) UpsertPushState(ctx context.Context, arg UpsertPushStateParams) (NotificationPushState, error) {
	row := q.db.QueryRow(ctx, upsertPushState,
		arg.UserID,
		arg.EventKey,
		arg.PushType,
		arg.LastSentAt,
		arg.PayloadHash,
	)
	var i NotificationPushState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventKey,
		&i.PushType,
		&i.LastSentAt,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
