// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BanUser(ctx context.Context, id uuid.UUID) error
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (int64, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrUpdateUserAIKey(ctx context.Context, arg CreateOrUpdateUserAIKeyParams) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserAIKey(ctx context.Context, arg DeleteUserAIKeyParams) error
	GetAuditLogByID(ctx context.Context, id int64) (AuditLog, error)
	GetLastAuditLog(ctx context.Context) (AuditLog, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationHistory(ctx context.Context, arg GetNotificationHistoryParams) ([]Notification, error)
	GetPasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordReset, error)
	GetRefreshToken(ctx context.Context, jti uuid.UUID) (RefreshToken, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetUnreadNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	GetUserAIKey(ctx context.Context, arg GetUserAIKeyParams) (UserAiKey, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	IsRefreshTokenRevoked(ctx context.Context, jti uuid.UUID) (bool, error)
	IsSessionRevoked(ctx context.Context, id uuid.UUID) (bool, error)
	ListActiveAIKeys(ctx context.Context) ([]UserAiKey, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkAllRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, id uuid.UUID) error
	MarkPasswordResetTokenConsumed(ctx context.Context, tokenHash []byte) error
	MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, jti uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	UnbanUser(ctx context.Context, id uuid.UUID) error
	UpdateAIKeyError(ctx context.Context, arg UpdateAIKeyErrorParams) error
	UpdateAIKeyHealth(ctx context.Context, arg UpdateAIKeyHealthParams) error
	UpdateAIKeyVerified(ctx context.Context, arg UpdateAIKeyVerifiedParams) error
	UpdateEmailVerifiedAt(ctx context.Context, arg UpdateEmailVerifiedAtParams) error
	UpdatePasswordVersion(ctx context.Context, id uuid.UUID) error
	UpdateSessionLastSeen(ctx context.Context, arg UpdateSessionLastSeenParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
