// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_alert_prefs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAlertPreferences = `-- name: GetUserAlertPreferences :one
SELECT user_id, currencies, symbols, impacts, reminder_minutes,
       high_impact_only,
       daily_digest_enabled, weekly_digest_enabled,
       cot_alerts_enabled, macro_alerts_enabled,
       options_alerts_enabled, onchain_alerts_enabled,
       updated_at
  FROM user_alert_preferences
 WHERE user_id = $1
`

func (q *Queries) GetUserAlertPreferences(ctx context.Context, userID uuid.UUID) (UserAlertPreference, error) {
	row := q.db.QueryRow(ctx, getUserAlertPreferences, userID)
	var i UserAlertPreference
	err := row.Scan(
		&i.UserID,
		&i.Currencies,
		&i.Symbols,
		&i.Impacts,
		&i.ReminderMinutes,
		&i.HighImpactOnly,
		&i.DailyDigestEnabled,
		&i.WeeklyDigestEnabled,
		&i.CotAlertsEnabled,
		&i.MacroAlertsEnabled,
		&i.OptionsAlertsEnabled,
		&i.OnchainAlertsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersWithAlertPrefs = `-- name: ListUsersWithAlertPrefs :many
SELECT u.id AS user_id,
       COALESCE(ap.currencies,           ARRAY['USD','EUR','GBP','JPY','CHF','CAD','AUD','NZD']::TEXT[])  AS currencies,
       COALESCE(ap.symbols,              ARRAY[]::TEXT[])                                                 AS symbols,
       COALESCE(ap.impacts,              ARRAY['high','medium']::TEXT[])                                  AS impacts,
       COALESCE(ap.reminder_minutes,     ARRAY[60,15]::INT[])                                            AS reminder_minutes,
       COALESCE(ap.high_impact_only,     FALSE)                                                           AS high_impact_only,
       COALESCE(ap.daily_digest_enabled, TRUE)                                                            AS daily_digest_enabled,
       COALESCE(ap.weekly_digest_enabled, TRUE)                                                           AS weekly_digest_enabled,
       COALESCE(ap.cot_alerts_enabled,   TRUE)                                                            AS cot_alerts_enabled,
       COALESCE(ap.macro_alerts_enabled, TRUE)                                                            AS macro_alerts_enabled,
       COALESCE(ap.options_alerts_enabled, TRUE)                                                          AS options_alerts_enabled,
       COALESCE(ap.onchain_alerts_enabled, TRUE)                                                          AS onchain_alerts_enabled,
       COALESCE(np.push_enabled,   TRUE)                                                                  AS push_enabled,
       COALESCE(np.min_severity,   'low')                                                                 AS min_severity,
       COALESCE(np.quiet_start,    '00:00')                                                               AS quiet_start,
       COALESCE(np.quiet_end,      '00:00')                                                               AS quiet_end,
       COALESCE(np.timezone,       'UTC')                                                                 AS timezone
  FROM users u
  LEFT JOIN user_alert_preferences ap ON ap.user_id = u.id
  LEFT JOIN user_notification_prefs np ON np.user_id = u.id
 WHERE u.id > $1   -- 游标分页（按 UUID 升序），避免 OFFSET 扫描膨胀
 ORDER BY u.id
 LIMIT $2
`

type ListUsersWithAlertPrefsParams struct {
	ID    uuid.UUID `json:"id"`
	Limit int32     `json:"limit"`
}

type ListUsersWithAlertPrefsRow struct {
	UserID               uuid.UUID   `json:"user_id"`
	Currencies           []string    `json:"currencies"`
	Symbols              []string    `json:"symbols"`
	Impacts              []string    `json:"impacts"`
	ReminderMinutes      []int32     `json:"reminder_minutes"`
	HighImpactOnly       bool        `json:"high_impact_only"`
	DailyDigestEnabled   bool        `json:"daily_digest_enabled"`
	WeeklyDigestEnabled  bool        `json:"weekly_digest_enabled"`
	CotAlertsEnabled     bool        `json:"cot_alerts_enabled"`
	MacroAlertsEnabled   bool        `json:"macro_alerts_enabled"`
	OptionsAlertsEnabled bool        `json:"options_alerts_enabled"`
	OnchainAlertsEnabled bool        `json:"onchain_alerts_enabled"`
	PushEnabled          bool        `json:"push_enabled"`
	MinSeverity          string      `json:"min_severity"`
	QuietStart           pgtype.Time `json:"quiet_start"`
	QuietEnd             pgtype.Time `json:"quiet_end"`
	Timezone             string      `json:"timezone"`
}

// 分批扫描用户（用于 digest 批量推送），返回有偏好的用户及偏好。
func (q *Queries) ListUsersWithAlertPrefs(ctx context.Context, arg ListUsersWithAlertPrefsParams) ([]ListUsersWithAlertPrefsRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithAlertPrefs, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithAlertPrefsRow
	for rows.Next() {
		var i ListUsersWithAlertPrefsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Currencies,
			&i.Symbols,
			&i.Impacts,
			&i.ReminderMinutes,
			&i.HighImpactOnly,
			&i.DailyDigestEnabled,
			&i.WeeklyDigestEnabled,
			&i.CotAlertsEnabled,
			&i.MacroAlertsEnabled,
			&i.OptionsAlertsEnabled,
			&i.OnchainAlertsEnabled,
			&i.PushEnabled,
			&i.MinSeverity,
			&i.QuietStart,
			&i.QuietEnd,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserAlertPreferences = `-- name: UpsertUserAlertPreferences :one
INSERT INTO user_alert_preferences (
    user_id, currencies, symbols, impacts, reminder_minutes,
    high_impact_only,
    daily_digest_enabled, weekly_digest_enabled,
    cot_alerts_enabled, macro_alerts_enabled,
    options_alerts_enabled, onchain_alerts_enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (user_id) DO UPDATE SET
    currencies             = EXCLUDED.currencies,
    symbols                = EXCLUDED.symbols,
    impacts                = EXCLUDED.impacts,
    reminder_minutes       = EXCLUDED.reminder_minutes,
    high_impact_only       = EXCLUDED.high_impact_only,
    daily_digest_enabled   = EXCLUDED.daily_digest_enabled,
    weekly_digest_enabled  = EXCLUDED.weekly_digest_enabled,
    cot_alerts_enabled     = EXCLUDED.cot_alerts_enabled,
    macro_alerts_enabled   = EXCLUDED.macro_alerts_enabled,
    options_alerts_enabled = EXCLUDED.options_alerts_enabled,
    onchain_alerts_enabled = EXCLUDED.onchain_alerts_enabled,
    updated_at             = NOW()
RETURNING user_id, currencies, symbols, impacts, reminder_minutes,
          high_impact_only,
          daily_digest_enabled, weekly_digest_enabled,
          cot_alerts_enabled, macro_alerts_enabled,
          options_alerts_enabled, onchain_alerts_enabled,
          updated_at
`

type UpsertUserAlertPreferencesParams struct {
	UserID               uuid.UUID `json:"user_id"`
	Currencies           []string  `json:"currencies"`
	Symbols              []string  `json:"symbols"`
	Impacts              []string  `json:"impacts"`
	ReminderMinutes      []int32   `json:"reminder_minutes"`
	HighImpactOnly       bool      `json:"high_impact_only"`
	DailyDigestEnabled   bool      `json:"daily_digest_enabled"`
	WeeklyDigestEnabled  bool      `json:"weekly_digest_enabled"`
	CotAlertsEnabled     bool      `json:"cot_alerts_enabled"`
	MacroAlertsEnabled   bool      `json:"macro_alerts_enabled"`
	OptionsAlertsEnabled bool      `json:"options_alerts_enabled"`
	OnchainAlertsEnabled bool      `json:"onchain_alerts_enabled"`
}

func (q *Queries) UpsertUserAlertPreferences(ctx context.Context, arg UpsertUserAlertPreferencesParams) (UserAlertPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserAlertPreferences,
		arg.UserID,
		arg.Currencies,
		arg.Symbols,
		arg.Impacts,
		arg.ReminderMinutes,
		arg.HighImpactOnly,
		arg.DailyDigestEnabled,
		arg.WeeklyDigestEnabled,
		arg.CotAlertsEnabled,
		arg.MacroAlertsEnabled,
		arg.OptionsAlertsEnabled,
		arg.OnchainAlertsEnabled,
	)
	var i UserAlertPreference
	err := row.Scan(
		&i.UserID,
		&i.Currencies,
		&i.Symbols,
		&i.Impacts,
		&i.ReminderMinutes,
		&i.HighImpactOnly,
		&i.DailyDigestEnabled,
		&i.WeeklyDigestEnabled,
		&i.CotAlertsEnabled,
		&i.MacroAlertsEnabled,
		&i.OptionsAlertsEnabled,
		&i.OnchainAlertsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
